export type customTheme = typeof darkTheme | typeof lightTheme;

export const darkTheme = {
  mode: "dark",
  PRIMARY_BACKGROUND_COLOR: "#293241",
  SECONDARY_BACKGROUND_COLOR: "#374358",
  PRIMARY_TEXT_COLOR: "#ffffff",
  PRIMARY_BUTTON_COLOR: "#98C1D9",
  PRIMARY_BUTTON_TEXT_COLOR: "#ffffff",
  PRIMARY_BUTTON_BACKGROUND_COLOR: "#F5F5F5",
  PRIMARY_ACCENT_COLOR: "#EE6C4D",
  STATUS_BAR_STYLE: "light",
};

export const lightTheme = {
  mode: "light",
  PRIMARY_BACKGROUND_COLOR: "#FFFFFF",
  SECONDARY_BACKGROUND_COLOR: "#FFFFFF",
  PRIMARY_TEXT_COLOR: "#293241",
  PRIMARY_BUTTON_COLOR: "#98C1D9",
  PRIMARY_BUTTON_TEXT_COLOR: "#ffffff",
  PRIMARY_BUTTON_BACKGROUND_COLOR: "#F5F5F5",
  PRIMARY_ACCENT_COLOR: "#EE6C4D",
  STATUS_BAR_STYLE: "dark",
};
